name: Bank DevSecOps Pipeline

on:
  pull_request:
  push:

jobs:

  ci_security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate project structure
        run: |
          if [ ! -d "anvar_a" ]; then
            echo "Folder missing!"
            exit 1
          fi
          echo "Structure OK"

      - name: Scan for secrets
        run: |
          if grep -r -iE "password|api_key|token" .; then
            echo "Sensitive data found!"
            exit 1
          else
            echo "No secrets found"
          fi

  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs

  deploy:
    runs-on: ubuntu-latest
    needs: [ci_security, security_scan]

    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate deployment
        run: |
          mkdir dist
          echo "Deployment successful" > dist/output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
