name: DevSecOps Pipeline

on:
  pull_request:
  push:

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check folder
        run: |
          if [ ! -d "anvar_a" ]; then
            echo "Folder missing!"
            exit 1
          fi

      - name: Scan for secrets
        run: |
          grep -r "password" . && echo "Warning found" || echo "Clean"

  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs

  cd:
    runs-on: ubuntu-latest
    needs: [ci, security]

    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir dist
          echo "Deployment successful" > dist/output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/
